name: ema

dependencies:
- python=3.6
- numpy
- scipy
- matplotlib
- seaborn
- pandas
- ipython
- ipyparallel
- jupyter
- pip:
  - ema_workbench
  - salib
  - git+https://github.com/Project-Platypus/Platypus.git

